[pytest]
norecursedirs =
    .pytest_cache
    pytest-cache-files-*
    tests/_tmp
    tests/pytest_tmp
    tests/.pytest_tmp
filterwarnings =
    ignore:the load_module\(\) method is deprecated.*:DeprecationWarning
    ignore:datetime\.datetime\.utcnow\(\) is deprecated.*:DeprecationWarning
