def build_rate(amount_original: object, amount_base: object, currency: str) -> float: ...
def budget_batch_spent_minor(
    db_path: str, budgets: list[tuple[int, str, str, str, str, bool]]
) -> list[tuple[int, int]]: ...
def budget_create(
    db_path: str,
    category: str,
    scope_type: str,
    scope_value: str,
    start_date: str,
    end_date: str,
    limit_base: float,
    limit_base_minor: int,
    include_mandatory: bool,
) -> dict[str, object]: ...
def budget_delete(db_path: str, budget_id: int) -> None: ...
def budget_overlap_exists(
    db_path: str,
    scope_type: str,
    scope_value: str,
    start_date: str,
    end_date: str,
    exclude_id: int | None = None,
) -> bool: ...
def budget_replace_rows(
    db_path: str,
    rows: list[tuple[int, str, str, str, float, int, bool, str, str]],
) -> None: ...
def budget_rows(db_path: str) -> list[dict[str, object]]: ...
def budget_spent_minor(
    db_path: str,
    scope_type: str,
    scope_value: str,
    start_date: str,
    end_date: str,
    include_mandatory: bool,
) -> int: ...
def budget_update_limit(
    db_path: str, budget_id: int, limit_base: float, limit_base_minor: int
) -> dict[str, object]: ...
def cashflow_sum(db_path: str, record_type: str, start_date: str, end_date: str) -> float: ...
def currency_default_rates_for_base(
    base_currency: str, rates: dict[str, float]
) -> dict[str, float]: ...
def currency_rate_for(currency: str, base_currency: str, rates: dict[str, float]) -> float: ...
def currency_resolve_provider_order(
    base_currency: str,
    provider_mode: str,
    primary_provider: str,
    fallback_provider: str,
    commercial_fallback_provider: str,
    enable_cbr: bool,
    provider_order: list[str] | None = None,
) -> list[str]: ...
def debt_payment_total_minor(db_path: str, debt_id: int) -> int: ...
def debt_recalculate_payload(db_path: str, debt_id: int) -> dict[str, object]: ...
def debt_validate_payment_amount(remaining_amount_minor: int, payment_amount_minor: int) -> int: ...
def distribution_available_months(db_path: str) -> list[str]: ...
def distribution_create_item(
    db_path: str, name: str, group_name: str, sort_order: int, pct: float, pct_minor: int
) -> dict[str, object]: ...
def distribution_create_subitem(
    db_path: str, item_id: int, name: str, sort_order: int, pct: float, pct_minor: int
) -> dict[str, object]: ...
def distribution_delete_item(db_path: str, item_id: int) -> None: ...
def distribution_delete_subitem(db_path: str, subitem_id: int) -> None: ...
def distribution_frozen_rows(
    db_path: str, start_month: str | None = None, end_month: str | None = None
) -> list[dict[str, object]]: ...
def distribution_history_months(db_path: str, start_month: str, end_month: str) -> list[str]: ...
def distribution_is_month_auto_fixed(db_path: str, month: str) -> bool: ...
def distribution_is_month_fixed(db_path: str, month: str) -> bool: ...
def distribution_item_rows(db_path: str, active_only: bool) -> list[dict[str, object]]: ...
def distribution_monthly_payload(
    db_path: str, month: str, start_date: str, end_date: str
) -> dict[str, object]: ...
def distribution_net_income_for_period(
    db_path: str, start_date: str, end_date: str
) -> tuple[float, int]: ...
def distribution_replace_frozen_rows(
    db_path: str,
    rows: list[tuple[str, list[str], list[tuple[str, str]], list[tuple[str, str]], bool, bool]],
) -> None: ...
def distribution_replace_structure(
    db_path: str,
    items: list[tuple[int, str, str, int, float, int, bool]],
    subitems: list[tuple[int, int, str, int, float, int, bool]],
) -> None: ...
def distribution_subitem_rows(
    db_path: str, item_id: int, active_only: bool
) -> list[dict[str, object]]: ...
def distribution_unfreeze_month(db_path: str, month: str) -> None: ...
def distribution_update_item_name(db_path: str, item_id: int, name: str) -> dict[str, object]: ...
def distribution_update_item_order(db_path: str, item_id: int, sort_order: int) -> None: ...
def distribution_update_item_pct(
    db_path: str, item_id: int, pct: float, pct_minor: int
) -> dict[str, object]: ...
def distribution_update_subitem_name(
    db_path: str, subitem_id: int, name: str
) -> dict[str, object]: ...
def distribution_update_subitem_order(db_path: str, subitem_id: int, sort_order: int) -> None: ...
def distribution_update_subitem_pct(
    db_path: str, subitem_id: int, pct: float, pct_minor: int
) -> dict[str, object]: ...
def distribution_validate_structure(db_path: str) -> list[dict[str, object]]: ...
def distribution_write_frozen_row(
    db_path: str,
    month: str,
    column_order: list[str],
    headings_by_column: list[tuple[str, str]],
    values_by_column: list[tuple[str, str]],
    is_negative: bool,
    auto_fixed: bool,
) -> None: ...
def metrics_burn_rate(db_path: str, start_date: str, end_date: str, days: int) -> float: ...
def metrics_income_by_category(
    db_path: str, start_date: str, end_date: str, limit: int | None = None
) -> list[dict[str, object]]: ...
def metrics_monthly_summary(
    db_path: str, start_date: str | None = None, end_date: str | None = None
) -> list[dict[str, object]]: ...
def metrics_period_snapshot(
    db_path: str,
    start_date: str,
    end_date: str,
    days: int,
    category_limit: int | None = None,
    tag_limit: int | None = None,
) -> dict[str, object]: ...
def metrics_period_snapshot_compact(
    db_path: str,
    start_date: str,
    end_date: str,
    days: int,
    category_limit: int | None = None,
    tag_limit: int | None = None,
) -> tuple[
    float,
    float,
    list[tuple[str, float, int]],
    list[tuple[str, float, int]],
    list[tuple[str, str, float, int]],
    tuple[int, int, float],
    list[tuple[str, float, float, float, float]],
    list[tuple[str, float, float, float]],
]: ...
def metrics_refresh_snapshot_compact(
    db_path: str,
    start_date: str,
    end_date: str,
    days: int,
    category_limit: int | None = None,
    tag_limit: int | None = None,
) -> tuple[
    float,
    float,
    list[tuple[str, float, int]],
    list[tuple[str, float, int]],
    list[tuple[str, str, float, int]],
    list[tuple[str, float, float, float, float]],
]: ...
def metrics_savings_rate(db_path: str, start_date: str, end_date: str) -> float: ...
def metrics_spending_by_category(
    db_path: str, start_date: str, end_date: str, limit: int | None = None
) -> list[dict[str, object]]: ...
def metrics_spending_by_tag(
    db_path: str, start_date: str, end_date: str, limit: int | None = None
) -> list[dict[str, object]]: ...
def metrics_tag_coverage(db_path: str, start_date: str, end_date: str) -> dict[str, object]: ...
def record_get_row(db_path: str, record_id: int) -> dict[str, object] | None: ...
def record_list_rows(
    db_path: str,
) -> list[dict[str, object]]: ...
def record_rows_by_tag(db_path: str, tag_name: str) -> list[dict[str, object]]: ...
def timeline_cumulative_income_expense(db_path: str) -> list[dict[str, object]]: ...
def timeline_monthly_cashflow(
    db_path: str, start_date: str | None = None, end_date: str | None = None
) -> list[dict[str, object]]: ...
def timeline_net_worth_monthly_deltas(db_path: str) -> list[dict[str, object]]: ...
def convert_amount(amount: float, rate: float) -> float: ...
def calculate_daily_burn(total_spent: float, days_passed: int) -> float: ...
def mandatory_expense_row(db_path: str, expense_id: int) -> dict[str, object] | None: ...
def mandatory_expense_rows(db_path: str) -> list[dict[str, object]]: ...
def minor_to_money(value: object) -> float: ...
def money_diff_text(left: object, right: object) -> str: ...
def money_abs(value: object) -> float: ...
def quantize_money_text(value: object) -> str: ...
def quantize_rate_text(value: object) -> str: ...
def rate_diff_text(left: object, right: object) -> str: ...
def rate_to_text(value: object) -> str: ...
def to_minor_units(value: object) -> int: ...
def to_money_float(value: object) -> float: ...
def to_rate_float(value: object) -> float: ...
def transfer_id_by_record_index(db_path: str, index: int) -> int | None: ...
def transfer_list_rows(db_path: str) -> list[dict[str, object]]: ...
def wallet_balance_parts(
    db_path: str, wallet_id: int, up_to_date: str | None = None
) -> tuple[float, str, float] | None: ...
def wallet_balance_rows(
    db_path: str, up_to_date: str | None = None
) -> list[tuple[int, str, str, float, float]]: ...
def wallet_list_rows(db_path: str) -> list[dict[str, object]]: ...
def storage_clear_read_cache() -> None: ...
