def build_rate(amount_original: object, amount_base: object, currency: str) -> float: ...
def cashflow_sum(db_path: str, record_type: str, start_date: str, end_date: str) -> float: ...
def record_get_row(db_path: str, record_id: int) -> dict[str, object] | None: ...
def record_list_rows(
    db_path: str,
) -> list[dict[str, object]]: ...
def record_rows_by_tag(db_path: str, tag_name: str) -> list[dict[str, object]]: ...
def convert_amount(amount: float, rate: float) -> float: ...
def calculate_daily_burn(total_spent: float, days_passed: int) -> float: ...
def minor_to_money(value: object) -> float: ...
def money_diff_text(left: object, right: object) -> str: ...
def money_abs(value: object) -> float: ...
def quantize_money_text(value: object) -> str: ...
def quantize_rate_text(value: object) -> str: ...
def rate_diff_text(left: object, right: object) -> str: ...
def rate_to_text(value: object) -> str: ...
def to_minor_units(value: object) -> int: ...
def to_money_float(value: object) -> float: ...
def to_rate_float(value: object) -> float: ...
def transfer_list_rows(db_path: str) -> list[dict[str, object]]: ...
def wallet_balance_parts(
    db_path: str, wallet_id: int, up_to_date: str | None = None
) -> tuple[float, str, float] | None: ...
def wallet_balance_rows(
    db_path: str, up_to_date: str | None = None
) -> list[tuple[int, str, str, float, float]]: ...
def wallet_list_rows(db_path: str) -> list[dict[str, object]]: ...
